/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package go_sudoku */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 15 "main.go"

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

// Bridge function declarations (implemented in bridge.c)
extern void api_message(const char *msg);
extern void *api_current_buffer(void);
extern void *api_find_buffer(const char *name);
extern void *api_buffer_create(const char *name);
extern int api_buffer_switch(void *bp);
extern int api_buffer_clear(void *bp);
extern int api_buffer_insert(const char *text, size_t len);
extern void api_get_point(int *line, int *col);
extern void api_set_point(int line, int col);
extern void api_log_info(const char *msg);
extern void api_log_error(const char *msg);
extern void api_update_display(void);
extern int api_prompt_yn(const char *prompt);

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// GoSudokuNew starts a new game
//
extern int GoSudokuNew(int f, int n);

// GoSudokuCheck checks for errors
//
extern int GoSudokuCheck(int f, int n);

// GoSudokuHint gives a hint
//
extern int GoSudokuHint(int f, int n);

// GoSudokuSolve shows the solution
//
extern int GoSudokuSolve(int f, int n);

// GoSudokuReset resets to original
//
extern int GoSudokuReset(int f, int n);

// GoSudokuInit initializes the extension
//
extern void GoSudokuInit(void);

// GoSudokuCleanup cleans up the extension
//
extern void GoSudokuCleanup(void);

#ifdef __cplusplus
}
#endif
