/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package go_lsp */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"

#include <stdlib.h>
#include <stdint.h>

// External functions from bridge.c
extern void api_message(const char *msg);
extern void api_log_info(const char *msg);
extern void api_log_error(const char *msg);
extern void* api_current_buffer(void);
extern const char* api_buffer_filename(void *bp);
extern char* api_buffer_contents(void *bp, size_t *len);
extern void api_get_point(int *line, int *col);
extern int api_find_file_line(const char *path, int line);
extern void* api_buffer_create(const char *name);
extern int api_buffer_switch(void *bp);
extern int api_buffer_clear(void *bp);
extern int api_buffer_insert(const char *text, size_t len);
extern void api_free(void *ptr);
extern int api_syntax_add_token(void *tokens, int end_col, int face);
extern void api_syntax_invalidate_buffer(void *bp);

// Diagnostic event types for linter integration
typedef struct {
    const char *uri;
    int line;
    int col;
    int end_col;
    int severity;
    const char *message;
} lsp_diag_entry_t;

extern void api_emit_diagnostics(const char *uri, lsp_diag_entry_t *diags, int count);

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern int go_lsp_start(int f, int n);
extern int go_lsp_stop(int f, int n);
extern int go_lsp_hover(int f, int n);
extern int go_lsp_definition(int f, int n);
extern int go_lsp_references(int f, int n);
extern int go_lsp_refresh_tokens(int f, int n);
extern int go_lsp_did_save(int f, int n);
extern int go_lsp_did_close(int f, int n);
extern int go_lsp_completion(int f, int n);
extern int go_lsp_diagnostics(int f, int n);
extern int go_lsp_code_action(int f, int n);
extern int go_lsp_document_symbols(int f, int n);
extern int go_lsp_workspace_symbols(int f, int n);

// Lexer callback - called from C for each line
extern void go_lsp_lex_line(void* userData, void* buffer, int lineNum, char* line, int lineLen, void* outTokens);

#ifdef __cplusplus
}
#endif
